### ISSUE TITLE
TK#06 Generar primera version de sitio web.

### ISSUE THREAD

**Issue by cesarweb** [FullStackCatamarca/proyecto_g2-proyecto_g2#33]

**Comment by JavierEspilocin** [comment]
https://miprimerproyectoweb2020.000webhostapp.com/index.html

**Comment by JavierEspilocin** [comment]
También subo las Carpetas de la primera versión del sitio para que entre todos la vamos modificando  

https://drive.google.com/file/d/1tzNcK7qagR6kn70pr1PTRLgDW-GQCWlG/view?usp=sharing

**Comment by JavierEspilocin** [comment]
Segunda Versión del sitio, ahora está en base a bootstrap 4 como pedia la profe, pero falta crear la pagina para el foro, clima, el back-end, modificar estilos, y seguir adaptando..

https://miprimerproyectoweb2020.000webhostapp.com/

**Comment by JavierEspilocin** [comment]
carpetas del sitio

https://drive.google.com/drive/folders/1h_JtyT3080u46i34OsVSlr5nPJBmJM_-?usp=sharing
